export class ContinentePaisUtils {

  static retornarContinentes() {
    return [
      { name: 'África', value: 'AFRICA' },
      { name: 'Ásia', value: 'ASIA' },
      { name: 'Europa', value: 'EUROPA' },
      { name: 'América', value: 'AMERICA' },
      { name: 'Oceania', value: 'OCEANIA' },
    ];
  }

  static retornarPaises() {
    return [
      { name: 'Afeganistão', value: 'AFEGANISTAO', continente : 'ASIA' },
      { name: 'África do Sul', value: 'AFRICA_DO_SUL', continente : 'AFRICA' },
      { name: 'Albânia', value: 'ALBANIA', continente : 'EUROPA' },
      { name: 'Alemanha', value: 'ALEMANHA', continente : 'EUROPA' },
      { name: 'Andorra', value: 'ANDORRA', continente : 'EUROPA' },
      { name: 'Angola', value: 'ANGOLA', continente : 'AFRICA' },
      { name: 'Antiga e Barbuda', value: 'ANTIGA_E_BARBUDA', continente : 'AMERICA' },
      { name: 'Arábia Saudita', value: 'ARABIA_SAUDITA', continente : 'ASIA' },
      { name: 'Argélia', value: 'ARGELIA', continente : 'AFRICA' },
      { name: 'Argentina', value: 'ARGENTINA', continente : 'AMERICA' },
      { name: 'Armênia', value: 'ARMENIA', continente : 'ASIA' },
      { name: 'Austrália', value: 'AUSTRALIA', continente : 'OCEANIA' },
      { name: 'Áustria', value: 'AUSTRIA', continente : 'EUROPA' },
      { name: 'Arzebaijão', value: 'AZERBAIJAO', continente : 'ASIA' },
      { name: 'Bahamas', value: 'BAHAMAS', continente : 'AMERICA' },
      { name: 'Bangladexe', value: 'BANGLADEXE', continente : 'ASIA' },
      { name: 'Barbados', value: 'BARBADOS', continente : 'AMERICA' },
      { name: 'Barem', value: 'BAREM', continente : 'ASIA' },
      { name: 'Bélgica', value: 'BELGICA', continente : 'EUROPA' },
      { name: 'Belize', value: 'BELIZE', continente : 'AMERICA' },
      { name: 'Benim', value: 'BENIM', continente : 'AFRICA' },
      { name: 'Bielorrusia', value: 'BIELORRUSSIA', continente : 'EUROPA' },
      { name: 'Bolívia', value: 'BOLIVIA', continente : 'AMERICA' },
      { name: 'Bósnia e Herzegovina', value: 'BOSNIA_E_HERZEGOVINA', continente : 'EUROPA' },
      { name: 'Botsuana', value: 'BOTSUANA', continente : 'AFRICA' },
      { name: 'Brasil', value: 'BRASIL', continente : 'AMERICA' },
      { name: 'BRUNEI', value: 'Brunei', continente : 'ASIA' },
      { name: 'Bulgária', value: 'BULGARIA', continente : 'EUROPA' },
      { name: 'Burquina Faso', value: 'BURQUINA_FASO', continente : 'AFRICA' },
      { name: 'BURUNDI', value: 'Burundi', continente : 'AFRICA' },
      { name: 'Butão', value: 'BUTAO', continente : 'ASIA' },
      { name: 'Cabo Verde', value: 'CABO_VERDE', continente : 'AFRICA' },
      { name: 'Camarões', value: 'CAMAROES', continente : 'AFRICA' },
      { name: 'Camboja', value: 'CAMBOJA', continente : 'ASIA' },
      { name: 'Canadá', value: 'CANADA', continente : 'AMERICA' },
      { name: 'Catar', value: 'CATAR', continente : 'ASIA' },
      { name: 'Cazaquistão', value: 'CAZAQUISTAO', continente : 'ASIA' },
      { name: 'Chade', value: 'CHADE', continente : 'AFRICA' },
      { name: 'Chile', value: 'CHILE', continente : 'AMERICA' },
      { name: 'China', value: 'CHINA', continente : 'ASIA' },
      { name: 'Chipre', value: 'CHIPRE', continente : 'EUROPA' },
      { name: 'Colômbia', value: 'COLOMBIA', continente : 'AMERICA' },
      { name: 'Comores', value: 'COMORES', continente : 'AFRICA' },
      { name: 'Congo Brazzaville', value: 'CONGO_BRAZZAVILLE', continente : 'AFRICA' },
      { name: 'Coréia do Norte', value: 'COREIA_DO_NORTE', continente : 'ASIA' },
      { name: 'Coréia do Sul', value: 'COREIA_DO_SUL', continente : 'ASIA' },
      { name: 'Cosovo', value: 'COSOVO', continente : 'EUROPA' },
      { name: 'Costa do Marfim', value: 'COSTA_DO_MARFIM', continente : 'AFRICA' },
      { name: 'Costa Rica', value: 'COSTA_RICA', continente : 'AMERICA' },
      { name: 'Croácia', value: 'CROACIA', continente : 'EUROPA' },
      { name: 'Cuaite', value: 'CUAITE', continente : 'ASIA' },
      { name: 'Cuba', value: 'CUBA', continente : 'ASIA' },
      { name: 'Dinamarca', value: 'DINAMARCA', continente : 'EUROPA' },
      { name: 'Dominica', value: 'DOMINICA', continente : 'AMERICA' },
      { name: 'Égito', value: 'EGITO', continente : 'AFRICA' },
      { name: 'Emirados Árabes Unidos', value: 'EMIRADOS_ARABES_UNIDOS', continente : 'ASIA' },
      { name: 'Equador', value: 'EQUADOR', continente : 'AMERICA' },
      { name: 'Eslováquia', value: 'ESLOVAQUIA', continente : 'EUROPA' },
      { name: 'Eslovênia', value: 'ESLOVENIA', continente : 'EUROPA' },
      { name: 'Espanha', value: 'ESPANHA', continente : 'EUROPA' },
      { name: 'Estados Unidos', value: 'ESTADOS_UNIDOS', continente : 'AMERICA' },
      { name: 'Finlândia', value: 'FINLANDIA', continente : 'EUROPA' },
      { name: 'França', value: 'FRANCA', continente : 'EUROPA' },
      { name: 'Gana', value: 'GANA', continente : 'AFRICA' },
      { name: 'Grécia', value: 'GRECIA', continente : 'EUROPA' },
      { name: 'Hungria', value: 'HUNGRIA', continente : 'EUROPA' },
      { name: 'Itália', value: 'ITALIA', continente : 'EUROPA' },
      { name: 'Japão', value: 'JAPAO', continente : 'ASIA' },
      { name: 'Letônia', value: 'LETONIA', continente : 'EUROPA' },
      { name: 'Listenstaine', value: 'LISTENSTAINE', continente : 'EUROPA' },
      { name: 'Luxemburgo', value: 'LUXEMBURGO', continente : 'EUROPA' },
      { name: 'Macedônia do Norte', value: 'MACEDONIA_DO_NORTE', continente : 'EUROPA' },
      { name: 'Malta', value: 'MALTA', continente : 'EUROPA' },
      { name: 'Marrocos', value: 'MARROCOS', continente : 'AFRICA' },
      { name: 'México', value: 'MEXICO', continente : 'AMERICA' },
      { name: 'Moldávia', value: 'MOLDAVIA', continente : 'EUROPA' },
      { name: 'Nigéria', value: 'NIGERIA', continente : 'AFRICA' },
      { name: 'Noruega', value: 'NORUEGA', continente : 'EUROPA' },
      { name: 'Nova Zelândia', value: 'NOVA_ZELANDIA', continente : 'OCEANIA' },
      { name: 'Holanda', value: 'HOLANDA', continente : 'EUROPA' },
      { name: 'Paraguai', value: 'PARAGUAI', continente : 'AMERICA' },
      { name: 'Peru', value: 'PERU', continente : 'AMERICA' },
      { name: 'Polônia', value: 'POLONIA', continente : 'EUROPA' },
      { name: 'Portugal', value: 'PORTUGAL', continente : 'EUROPA' },
      { name: 'Inglaterra', value: 'INGLATERRA', continente : 'EUROPA' },
      { name: 'Irlanda do Norte', value: 'IRLANDA_DO_NORTE', continente : 'EUROPA' },
      { name: 'Escócia', value: 'ESCOCIA', continente : 'EUROPA' },
      { name: 'País de Gales', value: 'PAIS_GALES', continente : 'EUROPA' },
      { name: 'República Checa', value: 'REPUBLICA_CHECA', continente : 'EUROPA' },
      { name: 'Romênia', value: 'ROMENIA', continente : 'EUROPA' },
      { name: 'Rússia', value: 'RUSSIA', continente : 'EUROPA' },
      { name: 'Senegal', value: 'SENEGAL', continente : 'AFRICA' },
      { name: 'Sérvia', value: 'SERVIA', continente : 'EUROPA' },
      { name: 'Suécia', value: 'SUECIA', continente : 'EUROPA' },
      { name: 'Suíça', value: 'SUICA', continente : 'EUROPA' },
      { name: 'Tunísia', value: 'TUNISIA', continente : 'AFRICA' },
      { name: 'Turquia', value: 'TURQUIA', continente : 'ASIA' },
      { name: 'Ucrânia', value: 'UCRANIA', continente : 'EUROPA' },
      { name: 'Uruguai', value: 'URUGUAI', continente : 'AMERICA' },
      { name: 'Venezuela', value: 'VENEZUELA', continente : 'AMERICA' },
    ];
  }
}
